apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: react-scan-pipelinerun
spec:
  params: 
    - name: "github-repo-revision"
      value: "main"
    - name: "github-repo-url"
      value: "https://github.com/shaneboulden/chains-pipeline.git"
    - name: "context-dir"
      value: "/"
    - name: "image"
      value: "example-registry-quay-quay.apps.rosa-mqc4s.nkv5.p1.openshiftapps.com/quayuser1/ubitest:v.9.5"

  pipelineRef:
    name: harden-ubi
  podTemplate:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      volumes:
        - name: varlibcontainers
          persistentVolumeClaim:
            claimName: containers-pvc
  serviceAccountName: pipeline-svc
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: pipeline-pvc